# Site
name: "Being Not Thinking"
title: "Being Not Thinking"
description: "A Lifestyle blog discussing Meditation, Art, and Living differently"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
domain: 'beingnotthinking.github.io'
url: 'https://beingnotthinking.github.io'
baseurl: ''
# google_analytics: 'UA-46278016-1'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

collections:
  art:
    output: true
    permalink: /:collection/:title
  meditation:
    output: true
    permalink: /:collection/:title

# Authors
authors:
  patrick:
    name: Patrick
    display_name: Patrick
    avatar: 'assets/images/patrick-avatar.png'
    email: beingnotthinking@gmail.com
    web: https://beingnotthinking.com
    twitter: https://twitter.com/beingntthinking
    description: "An eventual Description about Patrick"
  michaela:
    name: Michaela
    display_name: Michaela
    avatar: 'assets/images/michaela-avatar.png'
    email: beingnotthinking@gmail.com
    web: https://beingnotthinking.com
    twitter: https://twitter.com/beingntthinking
    description: "An eventual Description about Michaela"
  patrick-and-michaela:
    name: patrick-and-michaela
    display_name: Patrick and Michaela
    avatar: 'assets/images/patrick-and-michaela.png'
    email: beingnotthinking@gmail.com
    web: https://beingnotthinking.com
    twitter: https://twitter.com/beingntthinking
    description: "Us!"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
