[build]
  command = "npm run production"
  publish = "public"
  functions = "./netlify/functions/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
